#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/movzx.h"
#include "data-mov/movsx.h"
#include "data-mov/xchg.h"
#include "data-mov/push.h"
#include "data-mov/pop.h"

#include "jump/call.h"
#include "jump/call2.h"
#include "jump/je.h"
#include "jump/jne.h"
#include "jump/js.h"
#include "jump/jns.h"
#include "jump/jb.h"
#include "jump/jbe.h"
#include "jump/ja.h"
#include "jump/jae.h"
#include "jump/jl.h"
#include "jump/jle.h"
#include "jump/jg.h"
#include "jump/jge.h"
#include "jump/jmp.h"
#include "jump/jmp2.h"
#include "jump/leave.h"
#include "jump/ret.h"


#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/sub.h"
#include "arith/sbb.h"
#include "arith/test.h"
#include "arith/cmp.h"
#include "arith/add.h"
#include "arith/adc.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/shld.h"

#include "set/seta.h"
#include "set/setae.h"
#include "set/setb.h"
#include "set/setbe.h"
#include "set/sete.h"
#include "set/setg.h"
#include "set/setge.h"
#include "set/setl.h"
#include "set/setle.h"
#include "set/setne.h"
#include "set/setno.h"
#include "set/setnp.h"
#include "set/setns.h"
#include "set/seto.h"
#include "set/setp.h"
#include "set/sets.h"

#include "rep/movs.h"
#include "rep/cmps.h"
#include "rep/scas.h"
#include "rep/stos.h"


#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"
